version: '3.1'
services:
  adminer:
    image: gcmedia/adminer
    networks:
      - gcmedia-net
    ports:
      - "${ADMINER_PORT}"
    environment:
      - ADMINER_PORT=$ADMINER_PORT
    labels:
      - "traefik.backend=adminer"
      - "traefik.docker.network=gcmedia-net"
      - "traefik.enable=true"
      - "traefik.protocol=http"
      - "traefik.frontend.rule=Host:adminer.thegc.website"
      - "traefik.port=${ADMINER_PORT}"
networks:
  gcmedia-net:
    external: true
